<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Tags\Tag;

class TagSeeder extends Seeder
{
    public function run(): void
    {
        $keywords = [
            'Android Developer',
            'AWS Cloud Engineer',
            'AWS Solutions Architect',
            'AWS',
            'Backend Developer',
            'Backend Engineer',
            'Backend Shopify',
            'Backend',
            'C# .Net Developer',
            'C# Developer',
            'Database Administrator',
            'DevOps Architect',
            'DevOps Engineer',
            'DevOps',
            'Drupal',
            'Flutter Developer',
            'Front-end Engineer',
            'Frontend Developer',
            'Help Desk Support',
            'Help Desk',
            'iOS Developer',
            'IT Help Desk',
            'IT Support',
            'JavaScript Developer',
            'Laravel Developer',
            'Laravel',
            'Linux Administrator',
            'Linux SysAdmin',
            'Node.js Developer',
            'PHP Developer',
            'PHP Laravel Developer',
            'PHP programmer',
            'PHP',
            'Project Manager',
            'Python Developer',
            'Python Django',
            'Python Flask',
            'React Developer',
            'React JS',
            'React Native',
            'React Next.js Developer',
            'Ruby Developer',
            'Ruby on Rails',
            'Senior Software Engineer',
            'SEO Specialist',
            'Shopify Developer',
            'Software Developer',
            'Software Engineer',
            'Software Tester',
            'SQL Database Administrator',
            'SQL Developer',
            'Symfony',
            'SysAdmin',
            'System Administrator',
            'Technical Writer',
            'UI UX Designer',
            'Vue Nuxt Developer',
            'Vuejs Developer',
            'Web App Developer',
            'Web Developer',
            'WordPress Developer',
            'WordPress',
        ];

        foreach ($keywords as $keyword) {
            Tag::findOrCreate($keyword, 'keyword');
        }

        $skills = [
            'Ansible',
            'Apache',
            'ASP.NET Core',
            'Assembly',
            'C',
            'C#',
            'C++',
            'Cassandra',
            'CockroachDB',
            'CouchDB',
            'CSS',
            'Dart',
            'Django',
            'Docker',
            'DynamoDB',
            'Elasticsearch',
            'Express.js',
            'Flask',
            'Flutter',
            'Git',
            'Go',
            'HTML',
            'IBM DB2',
            'Java',
            'JavaScript',
            'K8s',
            'Kafka',
            'Kotlin',
            'Laravel',
            'Linux',
            'MariaDB',
            'Memcached',
            'MongoDB',
            'MS SQL Server',
            'MySQL',
            'Neo4j',
            'NestJS',
            'Next.js',
            'Nginx',
            'Node.js',
            'NoSQL',
            'Nuxt.js',
            'Oracle',
            'OrientDB',
            'Perl',
            'PHP',
            'PostgreSQL',
            'Python',
            'R',
            'RabbitMQ',
            'React',
            'Redis',
            'Ruby',
            'Ruby on Rails',
            'Rust',
            'SAP HANA',
            'Scala',
            'Spring Boot',
            'SQL',
            'SQLite',
            'Swift',
            'Tailwind',
            'TDD',
            'TypeScript',
            'Ubuntu',
            'Vue.js',
        ];

        foreach ($skills as $skill) {
            Tag::findOrCreate($skill, 'skill');
        }
    }
}
